- name: Run Black
  run: black .

- name: Commit changes
  run: |
    git config --global user.name "github-actions"
    git config --global user.email "github-actions@github.com"

    git add .
    git diff --staged --quiet || git commit -m "Format code with Black"
    git push